using System;
using System.Collections.Generic;
using System.Text;
//グラフを描画する
using ChartDirector;
//入出力
using System.IO;

namespace Test.Tremendous1192.SelfEmployed.CoMPASS.OtherNuGet
{
    public partial class ChartDirectorTest
    {
        public static void NoteCredits()
        {
            Console.WriteLine("\n" + "ChartDirector試用版に関する利用規約の引用");
            Console.WriteLine("The trial version of the ChartDirector software will produce yellow banner messages at the bottom of the chart images generated by it. You agree to not remove, obscure, or alter this message.");
            Console.WriteLine("Subjected to the conditions in this license agreement:");
            Console.WriteLine("・You may use the unmodified trial version of the ChartDirector software without charge.");
            Console.WriteLine("・You may redistribute the unmodified trial version of the ChartDirector software, provided you do not charge for it.");
            Console.WriteLine("・You may embed the unmodified trial version of the ChartDirector software (or part of it), in a product and distribute the product, provided you do not charge for the product.");
            Console.WriteLine("・If you do not want the yellow banner messages appearing in the charts, or you want to embed the ChartDirector software (or part of it) in a product that is not free, you must purchase a commercial license to use the ChartDirector software from Advanced Software Engineering Limited. Please refer to Advanced Software Engineering's web site at www.advsofteng.com for details.");
            Console.WriteLine("引用終わり" + "\n");
            Console.WriteLine("URL:" + "\t" + "https://www.advsofteng.com/doc/cdpydoc/license.htm" + "\n\n");

            Console.WriteLine("Credits");
            Console.WriteLine("This software is based in part on the work of the Independent JPEG Group");
            Console.WriteLine("This software is based in part of the work of the FreeType Team");
        }


    }
}
